### ISSUE TITLE
mixed output using threads

### ISSUE THREAD

**Issue by fero29** [badaix/aixlog#9]
Hi, I use 4 threads and sometimes is output mixed and logs inarticulate. Is exist any good practis how to use it is this situation?

**Comment by badaix** [comment]
It will mix the same way as std::cout does, since the stream if filled character by character, no matter from which thread. There is currently no workaround to avoid this.
I have a solution in mind, but it would be some coding effort (having a map from thread id to buffer, instead of a single buffer).

**Comment by fero29** [comment]
Ok, it would be counterproductive in my way. Thank you anyway
